project:
  type: website
  output-dir: docs

website:
  site-url: https://m-elzalabany.github.io/
 # title: "Manal K. Elzalabany"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: publications.qmd
        text: publications
      - icon: github
        href: https://github.com/manalkamal
      - icon: google
        href: https://scholar.google.com/citations?user=ojo0_24AAAAJ&hl=en
      # - icon: envelope
      #   href: mailto:
        
  page-footer: 
    left: 
      - "© 2024, Manal K. Elzalabany"

format:
  html:
    theme: 
      light: flatly
     # dark: slate
    css: styles.css
    toc: true

editor: visual

